name: Coverage
on:
  push:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup pnpm 
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: true
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache:  pnpm
    
    - run: pnpm run coverage
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
