name: project deploy

on:
  push:
    branches: [ "master" ]
    paths:
      - '**/*.md'
      - 'dumi/.dumirc.ts'
      - 'dumi/public/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '18.x'
    - name: Install
      run: npm install

    - name: Build doc
      run: npm run lib:doc
      
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v3
      with: 
        target_branch:  gh-pages
        build_dir:  dumi/dist
      env: 
        GITHUB_TOKEN: ${{ secrets.DOC_TOKEN }}
