# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Cure-ui publish

on:
  push:
    branches: [ "release" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm 
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache:  pnpm
      - name: build
        run:  |
          pnpm run lib:build
          pnpm run lib:types
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
